# ─────────────────────────────────────────────────────────────────────────────
# monitor rules
# ─────────────────────────────────────────────────────────────────────────────

monitorrule=name:^DP-,hdr:0,vrr:1
monitorrule=name:^DP-1,icc:"/usr/share/color/icc/colord/VG27WQ #1 2024-04-20 14-58 120cdm² D6500 2.2 M-S XYZLUT+MTX.icc",allow_tearing:1
monitorrule=name:^DP-4,icc:"/usr/share/color/icc/colord/U2515H #2 2024-04-20 16-02 120cdm² D6500 2.2 M-S XYZLUT+MTX.icc"
