# ─────────────────────────────────────────────────────────────────────────────
# tag rules
# ─────────────────────────────────────────────────────────────────────────────
# on all tags we open apps as floating clients
# available layouts: tile, scroller, grid, deck, monocle, center_tile, vertical_tile, vertical_scroller
tagrule=id:1,monitor_name:DP-1,layout_name:monocle
tagrule=id:1,monitor_name:DP-4,layout_name:monocle

tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# ─────────────────────────────────────────────────────────────────────────────
# layer rules
# ─────────────────────────────────────────────────────────────────────────────
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:fade,layer_name:rofi

# ─────────────────────────────────────────────────────────────────────────────
# window rules
# ─────────────────────────────────────────────────────────────────────────────
# commented as all apps are opened as floating clients (see before)
windowrule=isfloating:1,appid:auto-multiple-choice
windowrule=isfloating:1,appid:calibre-gui
windowrule=isfloating:1,appid:com.cisco.secureclient.gui
windowrule=isfloating:1,appid:com.nextcloud.desktopclient.nextcloud
windowrule=isfloating:1,appid:onboard
windowrule=isfloating:1,appid:thunar

windowrule=tags:1,monitor:DP-1,appid:brave-browser
windowrule=isfloating:1,appid:brave-browser,title:PayPal Checkout – Brave
windowrule=isfloating:1,appid:brave-browser,title:Connectez-vous à votre compte PayPal\s-\s[A-Za-z0-9]+

windowrule=tags:1,monitor:DP-4,appid:eu.betterbird.Betterbird
windowrule=isfloating:1,appid:eu.betterbird.Betterbird,title:À propos de Betterbird

windowrule=isfullscreen:1,appid:steam
windowrule=isfullscreen:1,title:Street Fighter 6

windowrule=isnamedscratchpad:1,width:1000,height:700,title:Joplin
