# ─────────────────────────────────────────────────────────────────────────────
# window rules
# ─────────────────────────────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────────────────────────────
# tag rules
# ─────────────────────────────────────────────────────────────────────────────
# on all tags we open apps as floating clients
# available layouts: tile, scroller, grid, deck, monocle, center_tile, vertical_tile, vertical_scroller
tagrule=id:1,layout_name:tile,open_as_floating:1
tagrule=id:2,layout_name:tile,open_as_floating:1
tagrule=id:3,layout_name:tile,open_as_floating:1
tagrule=id:4,layout_name:tile,open_as_floating:1
tagrule=id:5,layout_name:tile,open_as_floating:1
tagrule=id:6,layout_name:tile,open_as_floating:1
tagrule=id:7,layout_name:tile,open_as_floating:1
tagrule=id:8,layout_name:tile,open_as_floating:1
tagrule=id:9,layout_name:tile,open_as_floating:1

# ─────────────────────────────────────────────────────────────────────────────
# layer rules
# ─────────────────────────────────────────────────────────────────────────────
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:fade,layer_name:rofi

# ─────────────────────────────────────────────────────────────────────────────
# window rules
# ─────────────────────────────────────────────────────────────────────────────
# commented as all apps are opened as floating clients (see before)
# windowrule=isfloating:1,appid:auto-multiple-choice
# windowrule=isfloating:1,appid:calibre-gui
# windowrule=isfloating:1,appid:com.cisco.secureclient.gui
# windowrule=isfloating:1,appid:com.nextcloud.desktopclient.nextcloud
# windowrule=isfloating:1,appid:onboard
# windowrule=isfloating:1,appid:thunar
windowrule=isfloating:0,appid:brave-browser
windowrule=isfloating:1,appid:brave-browser,title:PayPal Checkout – Brave

windorule=isfullscreen:1,appid:steam
windorule=isfullscreen:1,title:Street Fighter 6

windowrule=isnamedscratchpad:1,width:1000,height:700,title:Joplin
